[Viewer]
Title = "MsGoBlog"
Description = "null"
Logo = "/resource/images/logo.png"
Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
Bilibili = "https://bilibili.com"
Zhihu = "https://www.zhihu.com/"
Avatar = "https://baidu.com"
UserName = "root"
UserDesc = "null"

[System]
CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
QiniuAccessKey = "替换自己的"
QiniuSecretKey = "替换自己的"
Valine = true
ValineAppid = "替换自己的"
ValineAppkey = "替换自己的"
ValineServerURL = "替换自己的"